const seedEntries = [
  {id:"e1",title:"Distributed index recovery notes",body:"WAL replay, shard leases, replica promotion, and recovery-time measurements for the search cluster.",type:"Note",tags:["search","reliability"],updated_at:new Date(Date.now()-12*60000).toISOString()},
  {id:"e2",title:"Reward misspecification in evaluation agents",body:"Observations from adversarial evaluation runs, including proxy gaming and out-of-distribution behavior.",type:"Paper",tags:["alignment","evaluation"],updated_at:new Date(Date.now()-86400000).toISOString()},
  {id:"e3",title:"BM25 relevance tuning, run 17",body:"Best result used k1 1.4 and b 0.72. Short queries improved while long-form retrieval remained stable.",type:"Run log",tags:["retrieval","benchmark"],updated_at:new Date(Date.now()-172800000).toISOString()},
  {id:"e4",title:"Streaming attribution architecture",body:"Partition strategy, idempotency keys, window watermarks, and late-event policy for campaign analytics.",type:"Note",tags:["kafka","analytics"],updated_at:new Date(Date.now()-345600000).toISOString()}
];
const seedRuns = [
  {id:"r1",name:"BM25 sweep 017",model:"BM25",dataset:"wiki-100k",status:"Running",score:.784,updated_at:new Date(Date.now()-180000).toISOString()},
  {id:"r2",name:"Reward audit 009",model:"Gemma-2B",dataset:"adversarial-2k",status:"Complete",score:.913,updated_at:new Date(Date.now()-7200000).toISOString()},
  {id:"r3",name:"Reranker baseline",model:"MiniLM",dataset:"msmarco-dev",status:"Queued",score:null,updated_at:new Date(Date.now()-14400000).toISOString()}
];
const state = {
  view:(location.hash||"#overview").slice(1),
  entries:load("atlas.entries",seedEntries), runs:load("atlas.runs",seedRuns),
  endpoint:load("atlas.endpoint","")||(location.port==="8088"?location.origin:""), connected:false, health:null, signals:null,
  query:"", filter:"All entries", mediaJobs:load("atlas.mediaJobs",[])
};
const titles = {
  overview:["Research overview","Your active work, systems, and signals in one place."],
  knowledge:["Knowledge index","Search papers, notes, and experiment logs together."],
  experiments:["Experiment registry","Track reproducible runs and compare outcomes."],
  signals:["System signals","Follow real latency, resource use, and recovery health."],
  media:["Media pipeline","Prepare demos and research artifacts for sharing."]
};

function load(key,fallback){try{const value=localStorage.getItem(key);return value?JSON.parse(value):fallback}catch{return fallback}}
function save(key,value){localStorage.setItem(key,JSON.stringify(value))}
function escapeHTML(value=""){return String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]))}
function relative(value){if(!value)return "Now";const seconds=Math.max(0,(Date.now()-new Date(value).getTime())/1000);if(seconds<60)return "Now";if(seconds<3600)return `${Math.floor(seconds/60)}m`;if(seconds<86400)return `${Math.floor(seconds/3600)}h`;return `${Math.floor(seconds/86400)}d`}
function api(path,options={}){return fetch(`${state.endpoint}${path}`,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}}).then(async response=>{if(!response.ok)throw new Error((await response.text())||response.statusText);return response.status===204?null:response.json()})}
function modeLabel(){return state.connected?"Connected runtime":"Browser mode"}
function heading(actions=""){const [title,copy]=titles[state.view]||titles.overview;return `<section class="page-heading"><div><p class="eyebrow">${state.connected?"Live workspace":"Private browser workspace"}</p><h1>${title}</h1><p>${copy}</p></div><div class="heading-actions">${actions}<button class="button primary" data-action="new-entry">＋ New entry</button></div></section>`}

async function connect(){
  if(!state.endpoint){state.connected=false;renderRuntime();return}
  try{
    state.health=await api("/api/health"); state.connected=true;
    const [entries,runs,signals]=await Promise.all([api("/api/entries"),api("/api/runs"),api("/api/signals")]);
    state.entries=entries.entries||[]; state.runs=runs.runs||[]; state.signals=signals; renderRuntime(); render();
  }catch(error){state.connected=false;renderRuntime();toast(`Runtime unavailable: ${error.message}`)}
}
function renderRuntime(){
  const button=document.querySelector("#runtimeButton");
  button.innerHTML=`<i class="status-dot ${state.connected?"live":""}"></i><span><strong>${modeLabel()}</strong><small>${state.connected?escapeHTML(state.endpoint.replace(/^https?:\/\//,"")):"Stored on this device"}</small></span><span>›</span>`;
  document.querySelector("#systemState").innerHTML=`<i class="status-dot ${state.connected?"live":""}"></i>${state.connected?"Runtime healthy":"Demo telemetry"}`;
}
function render(){
  document.querySelectorAll(".nav-item").forEach(button=>button.classList.toggle("active",button.dataset.view===state.view));
  const views={overview:overviewView,knowledge:knowledgeView,experiments:experimentsView,signals:signalsView,media:mediaView};
  document.querySelector("#workspace").innerHTML=(views[state.view]||overviewView)();
  bindView();
}
function overviewView(){
  const running=state.runs.filter(run=>run.status==="Running").length;
  const p95=state.connected&&state.signals?`${Math.max(1,Math.round(state.signals.search_p95_microseconds/1000))} ms`:"42 ms";
  return heading()+`<section class="metric-grid">
    ${metric("Indexed knowledge",state.entries.length,"Searchable entries","violet")}
    ${metric("Active experiments",running,`${state.runs.length} tracked runs`,"cyan")}
    ${metric("Search p95",p95,state.connected?`${state.signals?.search_samples||0} measured queries`:"Sample telemetry","amber")}
    ${metric("Runtime requests",state.connected?(state.signals?.requests||0):"1.28k",state.connected?"Since startup":"Sample telemetry","green")}
  </section><section class="dashboard-grid">
    <article class="panel chart-panel"><div class="panel-head"><div><p>Retrieval traffic</p><h2>Queries and latency</h2></div><span>${state.connected?"Measured locally":"Sample data"}</span></div><div class="chart"><i style="height:34%"></i><i style="height:42%"></i><i style="height:37%"></i><i style="height:58%"></i><i style="height:51%"></i><i style="height:72%"></i><i style="height:64%"></i><i style="height:81%"></i><i style="height:76%"></i><i style="height:92%"></i><i style="height:86%"></i><i style="height:98%"></i></div><div class="axis"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>Now</span></div></article>
    <article class="panel systems-panel"><div class="panel-head"><div><p>Runtime health</p><h2>Core systems</h2></div><button data-view-link="signals">Inspect ›</button></div>${systems()}</article>
    <article class="panel recent-panel"><div class="panel-head"><div><p>Workspace</p><h2>Recently indexed</h2></div><button data-view-link="knowledge">View all ›</button></div>${state.entries.slice(0,3).map(entry=>entryRow(entry)).join("")||empty("No entries indexed")}</article>
    <article class="panel run-panel"><div class="panel-head"><div><p>Experiments</p><h2>Active runs</h2></div><button data-view-link="experiments">Registry ›</button></div>${state.runs.slice(0,3).map(run=>`<div class="compact-row"><i class="run-dot ${run.status.toLowerCase()}"></i><span><strong>${escapeHTML(run.name)}</strong><small>${escapeHTML(run.model)} · ${escapeHTML(run.dataset)}</small></span><em>${relative(run.updated_at)}</em></div>`).join("")||empty("No runs tracked")}</article>
  </section>`;
}
function metric(label,value,copy,color){return `<article class="metric-card"><div class="metric-symbol ${color}">◇</div><p>${label}</p><strong>${value}</strong><small>${copy}</small></article>`}
function systems(){const data=state.connected?[{name:"Knowledge index",detail:`${state.health?.documents||0} indexed documents`,load:72},{name:"Metric store",detail:`${state.health?.metric_series||0} active series`,load:46},{name:"Catalog",detail:`${state.health?.entries||0} entries · ${state.health?.runs||0} runs`,load:61},{name:"Media queue",detail:"Resumable uploads ready",load:32}]:[{name:"Search index",detail:"BM25 · WAL recovery",load:72},{name:"Raft store",detail:"Replicated metadata",load:49},{name:"Event stream",detail:"Windowed analytics",load:63},{name:"Media workers",detail:"Lease-based processing",load:34}];return data.map(item=>`<div class="system-row"><span class="system-icon">▧</span><div><strong>${item.name}</strong><small>${item.detail}</small><div class="track"><i style="width:${item.load}%"></i></div></div><em>Healthy</em></div>`).join("")}
function entryRow(entry){return `<button class="entry-row" data-view-link="knowledge"><span class="type ${entry.type.toLowerCase().replace(" ","-")}">${entry.type[0]}</span><span><strong>${escapeHTML(entry.title)}</strong><small>${escapeHTML(entry.type)} · ${relative(entry.updated_at)}</small></span><b>›</b></button>`}

function applyFilter(entries){const singular={Papers:"Paper",Notes:"Note","Run logs":"Run log"}[state.filter];return singular?entries.filter(entry=>entry.type===singular):entries}
function localSearch(query){const words=query.toLowerCase().split(/\s+/).filter(Boolean);if(!words.length)return applyFilter(state.entries);return applyFilter(state.entries.map(entry=>{const title=entry.title.toLowerCase(),text=`${entry.title} ${entry.body} ${(entry.tags||[]).join(" ")}`.toLowerCase();return{entry,score:words.reduce((sum,word)=>sum+(title.includes(word)?3:0)+(text.includes(word)?1:0),0)}}).filter(item=>item.score).sort((a,b)=>b.score-a.score).map(item=>item.entry))}
function knowledgeView(){const results=localSearch(state.query);return heading()+`<section class="panel knowledge-panel"><div class="large-search"><span>⌕</span><input id="knowledgeSearch" value="${escapeHTML(state.query)}" placeholder="Search by idea, method, tag, or result"><em>${results.length} matches</em></div><div class="filters">${["All entries","Papers","Notes","Run logs"].map(filter=>`<button class="${filter===state.filter?"active":""}" data-filter="${filter}">${filter}</button>`).join("")}</div><div id="searchResults" class="results">${resultHTML(results)}</div></section>`}
function resultHTML(results){return results.map(entry=>`<article><span class="type ${entry.type.toLowerCase().replace(" ","-")}">${entry.type[0]}</span><div><div class="result-meta"><span>${escapeHTML(entry.type)}</span><span>${relative(entry.updated_at)}</span></div><h2>${escapeHTML(entry.title)}</h2><p>${escapeHTML(entry.body)}</p><div class="tags">${(entry.tags||[]).map(tag=>`<span>${escapeHTML(tag)}</span>`).join("")}</div></div></article>`).join("")||empty("No indexed entry matches your search")}

function experimentsView(){return heading(`<button class="button secondary" data-action="new-run">◇ Start run</button>`)+`<section class="panel table-panel"><div class="table-toolbar"><span>Experiment records are durable in connected mode</span><em>${state.runs.length} runs</em></div><div class="run-table"><div class="table-row header"><span>Run</span><span>Model</span><span>Dataset</span><span>Status</span><span>Score</span><span>Updated</span></div>${state.runs.map(run=>`<div class="table-row"><span><strong>${escapeHTML(run.name)}</strong><small>#${escapeHTML(run.id.slice(0,8))}</small></span><span>${escapeHTML(run.model||"Not set")}</span><span>${escapeHTML(run.dataset||"Not set")}</span><span><i class="chip ${run.status.toLowerCase()}">${escapeHTML(run.status)}</i></span><span>${typeof run.score==="number"?run.score.toFixed(3):"Pending"}</span><span>${relative(run.updated_at)}</span></div>`).join("")}</div></section>`}
function signalsView(){const signals=state.signals||{requests:1280,goroutines:12,heap_bytes:18600000,search_p95_microseconds:42000,search_samples:180,uptime_seconds:4800};const rows=[{name:"Search p95",value:Math.max(1,Math.round(signals.search_p95_microseconds/1000)),unit:"ms",max:100},{name:"Heap allocation",value:Math.round(signals.heap_bytes/1048576),unit:"MB",max:128},{name:"Goroutines",value:signals.goroutines,unit:"active",max:100},{name:"Metric series",value:signals.metric_series||0,unit:"series",max:50},{name:"Uptime",value:Math.round(signals.uptime_seconds/60),unit:"min",max:240}];return heading()+`<div class="signal-grid"><section class="panel latency-panel"><div class="panel-head"><div><p>${state.connected?"Live runtime":"Sample telemetry"}</p><h2>Operational signals</h2></div><span class="live-badge"><i></i>${state.connected?"Live":"Demo"}</span></div>${rows.map(row=>`<div class="signal-row"><span>${row.name}</span><div><i style="width:${Math.min(100,row.value/row.max*100)}%"></i></div><strong>${row.value} ${row.unit}</strong></div>`).join("")}</section><section class="panel"><div class="panel-head"><div><p>Recovery design</p><h2>Failure controls</h2></div></div>${["Search writes replay from WAL","Catalog updates use atomic rename","Metric samples recover from WAL","Media jobs use expiring leases","Raft writes require quorum"].map((text,index)=>`<div class="event-row"><i class="${index===0?"warn":""}"></i><span><strong>${text}</strong><small>Verified by automated tests</small></span></div>`).join("")}</section></div>`}
function mediaView(){return heading()+`<div class="media-grid"><label class="upload-zone"><input id="mediaFile" type="file" accept="video/*"><span class="upload-icon">⇧</span><h2>Prepare a research demo</h2><p>Upload a recording for resumable processing into web-ready HLS renditions.</p><span class="button secondary">Choose video</span><small>${state.connected?"The file will upload in 1 MB resumable chunks.":"Browser mode simulates the workflow without transferring your file."}</small></label><section class="panel"><div class="panel-head"><div><p>Pipeline</p><h2>Recent jobs</h2></div></div><div id="mediaJobs">${mediaJobsHTML()}</div></section></div>`}
function mediaJobsHTML(){const jobs=state.mediaJobs.length?state.mediaJobs:[{id:"sample-1",name:"research-demo-final.mp4",status:"Complete",progress:100,size:"284 MB"},{id:"sample-2",name:"retrieval-walkthrough.mov",status:"Processing",progress:67,size:"1.2 GB"}];return jobs.map(job=>`<div class="media-job"><span class="media-thumb">▷</span><div><strong>${escapeHTML(job.name)}</strong><small>${escapeHTML(job.size||"")} · ${escapeHTML(job.status)}</small><div class="progress"><i style="width:${job.progress}%"></i></div></div><em>${job.progress}%</em></div>`).join("")}
function empty(text){return `<div class="empty">${escapeHTML(text)}</div>`}

function bindView(){
  document.querySelectorAll("[data-view-link]").forEach(button=>button.addEventListener("click",()=>setView(button.dataset.viewLink)));
  document.querySelectorAll("[data-action='new-entry']").forEach(button=>button.addEventListener("click",entryModal));
  document.querySelectorAll("[data-action='new-run']").forEach(button=>button.addEventListener("click",runModal));
  const search=document.querySelector("#knowledgeSearch");if(search)search.addEventListener("input",async event=>{state.query=event.target.value;let results=localSearch(state.query);if(state.connected&&state.query.trim()){try{const data=await api(`/api/search?q=${encodeURIComponent(state.query)}&limit=30`);results=data.results.map(item=>item.entry)}catch{}}document.querySelector("#searchResults").innerHTML=resultHTML(results)});
  document.querySelectorAll("[data-filter]").forEach(button=>button.addEventListener("click",()=>{state.filter=button.dataset.filter;render()}));
  const file=document.querySelector("#mediaFile");if(file)file.addEventListener("change",event=>event.target.files[0]&&uploadMedia(event.target.files[0]));
}
function setView(view){state.view=view;location.hash=view;render()}
function modal(content){document.querySelector("#modalRoot").innerHTML=`<div class="modal-backdrop"><section class="modal">${content}</section></div>`;document.querySelector(".modal-backdrop").addEventListener("mousedown",event=>event.target===event.currentTarget&&closeModal());document.querySelectorAll("[data-close]").forEach(button=>button.addEventListener("click",closeModal))}
function closeModal(){document.querySelector("#modalRoot").innerHTML=""}
function entryModal(){modal(`<button class="modal-close" data-close>×</button><p class="modal-kicker">Atlas workspace</p><h2>Index a new entry</h2><p class="modal-copy">Add material you want to retrieve alongside papers and experiment logs.</p><form id="entryForm" class="form"><label>Title<input name="title" autofocus required placeholder="Evaluation protocol notes"></label><label>Type<select name="type"><option>Note</option><option>Paper</option><option>Run log</option></select></label><label>Content<textarea name="body" rows="4" placeholder="Key ideas, findings, or decisions"></textarea></label><label>Tags<input name="tags" placeholder="evaluation, retrieval, benchmark"></label><div class="form-actions"><button type="button" class="button ghost" data-close>Cancel</button><button class="button primary">Index entry</button></div></form>`);document.querySelector("#entryForm").addEventListener("submit",saveEntry);document.querySelector("#entryForm input").focus()}
async function saveEntry(event){event.preventDefault();const data=new FormData(event.target);let entry={title:data.get("title").trim(),type:data.get("type"),body:data.get("body").trim(),tags:data.get("tags").split(",").map(tag=>tag.trim()).filter(Boolean)};try{if(state.connected){entry=(await api("/api/entries",{method:"POST",body:JSON.stringify(entry)})).entry}else{entry={...entry,id:crypto.randomUUID(),created_at:new Date().toISOString(),updated_at:new Date().toISOString()};state.entries.unshift(entry);save("atlas.entries",state.entries)}closeModal();render();toast(state.connected?"Entry persisted and indexed":"Entry indexed on this device")}catch(error){toast(error.message)}}
function runModal(){modal(`<button class="modal-close" data-close>×</button><p class="modal-kicker">Experiment registry</p><h2>Track a new run</h2><p class="modal-copy">Keep the model, dataset, status, score, and notes together for reproducibility.</p><form id="runForm" class="form"><label>Run name<input name="name" autofocus required placeholder="Retrieval sweep 018"></label><div class="form-split"><label>Model<input name="model" placeholder="BM25"></label><label>Dataset<input name="dataset" placeholder="wiki-100k"></label></div><label>Status<select name="status"><option>Running</option><option>Queued</option><option>Complete</option></select></label><label>Notes<textarea name="notes" rows="3" placeholder="Hypothesis or configuration"></textarea></label><div class="form-actions"><button type="button" class="button ghost" data-close>Cancel</button><button class="button primary">Create run</button></div></form>`);document.querySelector("#runForm").addEventListener("submit",saveRun);document.querySelector("#runForm input").focus()}
async function saveRun(event){event.preventDefault();const data=new FormData(event.target);let run={name:data.get("name").trim(),model:data.get("model").trim(),dataset:data.get("dataset").trim(),status:data.get("status"),notes:data.get("notes").trim()};try{if(state.connected){run=(await api("/api/runs",{method:"POST",body:JSON.stringify(run)})).run}else{run={...run,id:crypto.randomUUID(),created_at:new Date().toISOString(),updated_at:new Date().toISOString()};state.runs.unshift(run);save("atlas.runs",state.runs)}closeModal();render();toast("Experiment registered")}catch(error){toast(error.message)}}
function connectionModal(){modal(`<button class="modal-close" data-close>×</button><p class="modal-kicker">Atlas runtime</p><h2>Connect your local service</h2><p class="modal-copy">Run <code>make atlas</code>, then enter its address for durable storage and real telemetry.</p><form id="connectionForm" class="form"><label>Atlas API URL<input name="endpoint" type="url" value="${escapeHTML(state.endpoint)}" placeholder="http://localhost:8088"></label><div class="connection-note"><strong>Browser mode remains available.</strong><span>Leave this blank to keep your workspace in browser storage.</span></div><div class="form-actions"><button type="button" class="button ghost" data-close>Cancel</button><button class="button primary">Save connection</button></div></form>`);document.querySelector("#connectionForm").addEventListener("submit",async event=>{event.preventDefault();state.endpoint=new FormData(event.target).get("endpoint").trim().replace(/\/$/,"");save("atlas.endpoint",state.endpoint);closeModal();await connect();render()})}
function commandModal(){modal(`<div class="command-input"><span>⌕</span><input id="commandSearch" autofocus placeholder="Go to a workspace"><kbd>ESC</kbd></div><p class="command-label">Navigate</p>${Object.keys(titles).map((view,index)=>`<button class="command-item" data-command-view="${view}"><span>${index+1}. ${titles[view][0]}</span><kbd>${index+1}</kbd></button>`).join("")}`);document.querySelectorAll("[data-command-view]").forEach(button=>button.addEventListener("click",()=>{closeModal();setView(button.dataset.commandView)}));document.querySelector("#commandSearch").focus()}
async function uploadMedia(file){const job={id:crypto.randomUUID(),name:file.name,status:state.connected?"Uploading":"Demo queued",progress:5,size:`${(file.size/1048576).toFixed(1)} MB`};state.mediaJobs.unshift(job);save("atlas.mediaJobs",state.mediaJobs);render();if(!state.connected){setTimeout(()=>{job.status="Demo complete";job.progress=100;save("atlas.mediaJobs",state.mediaJobs);state.view==="media"&&render();toast("Browser-mode media workflow complete")},900);return}try{const created=await api("/api/video/v1/uploads",{method:"POST"});const id=created.upload_id;let offset=0;const chunkSize=1048576;while(offset<file.size){const chunk=file.slice(offset,offset+chunkSize);const response=await fetch(`${state.endpoint}/api/video/v1/uploads/${id}`,{method:"PATCH",headers:{"Upload-Offset":String(offset)},body:chunk});if(!response.ok)throw new Error(await response.text());offset=Number(response.headers.get("Upload-Offset"));job.progress=Math.max(5,Math.round(offset/file.size*90));state.view==="media"&&render()}await api(`/api/video/v1/uploads/${id}/complete`,{method:"POST",headers:{"Idempotency-Key":`atlas:${file.name}:${file.size}`}});job.status="Queued";job.progress=100;save("atlas.mediaJobs",state.mediaJobs);render();toast("Video uploaded and processing job queued")}catch(error){job.status="Failed";save("atlas.mediaJobs",state.mediaJobs);render();toast(error.message)}}
function toast(message){const element=document.querySelector("#toast");element.textContent=message;element.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>element.classList.remove("show"),2800)}

document.querySelectorAll(".nav-item").forEach(button=>button.addEventListener("click",()=>setView(button.dataset.view)));
document.querySelector("#runtimeButton").addEventListener("click",connectionModal);
document.querySelector("#commandButton").addEventListener("click",commandModal);
window.addEventListener("hashchange",()=>{state.view=(location.hash||"#overview").slice(1);render()});
window.addEventListener("keydown",event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();commandModal()}if(event.key==="Escape")closeModal();if(!event.metaKey&&!event.ctrlKey&&!event.altKey&&/^[1-5]$/.test(event.key)&&!["INPUT","TEXTAREA","SELECT"].includes(document.activeElement?.tagName||""))setView(Object.keys(titles)[Number(event.key)-1])});
renderRuntime();render();connect();
